export const counterAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "initialOwner", type: "address", internalType: "address" },
      { name: "initialSigner", type: "address", internalType: "address" },
      { name: "rewardToken_", type: "address", internalType: "address" },
      { name: "rewardPerTap_", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address", internalType: "address" }] },
  { type: "error", name: "OwnableUnauthorizedAccount", inputs: [{ name: "account", type: "address", internalType: "address" }] },
  {
    type: "event",
    name: "Incremented",
    anonymous: false,
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      { name: "fid", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "nonce", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "reward", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "totalIncrements", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "userTotal", type: "uint256", indexed: false, internalType: "uint256" },
    ],
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    anonymous: false,
    inputs: [
      { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
      { name: "newOwner", type: "address", indexed: true, internalType: "address" },
    ],
  },
  {
    type: "event",
    name: "SignerUpdated",
    anonymous: false,
    inputs: [{ name: "newSigner", type: "address", indexed: true, internalType: "address" }],
  },
  {
    type: "function",
    name: "COOLDOWN",
    stateMutability: "view",
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    inputs: [],
  },
  {
    type: "function",
    name: "getUserData",
    stateMutability: "view",
    outputs: [
      { name: "count", type: "uint256", internalType: "uint256" },
      { name: "availableAt", type: "uint256", internalType: "uint256" },
    ],
    inputs: [{ name: "fid", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "increment",
    stateMutability: "nonpayable",
    outputs: [],
    inputs: [
      {
        name: "req",
        type: "tuple",
        internalType: "struct FarCounter.IncrementRequest",
        components: [
          { name: "user", type: "address", internalType: "address" },
          { name: "fid", type: "uint256", internalType: "uint256" },
          { name: "nonce", type: "uint256", internalType: "uint256" },
          { name: "deadline", type: "uint256", internalType: "uint256" },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    name: "lastIncrementAt",
    stateMutability: "view",
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "nextAvailableAt",
    stateMutability: "view",
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    inputs: [{ name: "fid", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "nonceUsed",
    stateMutability: "view",
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    outputs: [{ name: "", type: "address", internalType: "address" }],
    inputs: [],
  },
  {
    type: "function",
    name: "renounceOwnership",
    stateMutability: "nonpayable",
    outputs: [],
    inputs: [],
  },
  {
    type: "function",
    name: "rescueTokens",
    stateMutability: "nonpayable",
    outputs: [],
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    name: "rewardPerTap",
    stateMutability: "view",
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    inputs: [],
  },
  {
    type: "function",
    name: "rewardToken",
    stateMutability: "view",
    outputs: [{ name: "", type: "address", internalType: "address" }],
    inputs: [],
  },
  {
    type: "function",
    name: "setRewardPerTap",
    stateMutability: "nonpayable",
    outputs: [],
    inputs: [{ name: "newReward", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "setSigner",
    stateMutability: "nonpayable",
    outputs: [],
    inputs: [{ name: "newSigner", type: "address", internalType: "address" }],
  },
  {
    type: "function",
    name: "signer",
    stateMutability: "view",
    outputs: [{ name: "", type: "address", internalType: "address" }],
    inputs: [],
  },
  {
    type: "function",
    name: "totalIncrements",
    stateMutability: "view",
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    inputs: [],
  },
  {
    type: "function",
    name: "transferOwnership",
    stateMutability: "nonpayable",
    outputs: [],
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
  },
  {
    type: "function",
    name: "userIncrements",
    stateMutability: "view",
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
] as const;
